export const SEED_COMPANIES = [
  { name: "Stripe", boardToken: "stripe" },
  { name: "Anthropic", boardToken: "anthropic" },
  { name: "Vercel", boardToken: "vercel" },
  { name: "Airbnb", boardToken: "airbnb" },
  { name: "Cloudflare", boardToken: "cloudflare" },
  { name: "Robinhood", boardToken: "robinhood" },
  { name: "Discord", boardToken: "discord" },
  { name: "Notion", boardToken: "notion" },
  { name: "OpenAI", boardToken: "openai" },
  { name: "Figma", boardToken: "figma" },
  { name: "Linear", boardToken: "linear" },
  { name: "Plaid", boardToken: "plaid" },
  { name: "Brex", boardToken: "brex" },
  { name: "Ramp", boardToken: "ramp" },
  { name: "Mercury", boardToken: "mercury" },
  { name: "Retool", boardToken: "retool" },
  { name: "Scale", boardToken: "scaleai" },
  { name: "Webflow", boardToken: "webflow" },
  { name: "Coinbase", boardToken: "coinbase" },
  { name: "Reddit", boardToken: "reddit" },
];